name: housing
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.2.7=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38hc512035_1
  - chardet=3.0.4=py38_1003
  - click=7.0=py_0
  - cryptography=2.9.2=py38ha12b0ac_0
  - django=3.0.3=py_0
  - flask=1.1.1=py_1
  - flask-cors=3.0.8=py_0
  - flask-socketio=4.2.1=py_0
  - freetype=2.10.2=ha233b18_0
  - httplib2=0.17.0=py38h32f6830_1
  - idna=2.8=py38_1000
  - intel-openmp=2019.4=233
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=he5867d9_2
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=haf1e3a3_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h0a44026_0
  - markupsafe=1.1.1=py38h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h3304bdc_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h1de35cc_0
  - pandas=1.0.1=py38h6c726b0_0
  - pillow=7.0.0=py38h4655f20_0
  - pip=20.1.1=py38_1
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py38_0
  - pysocks=1.7.1=py38_0
  - python=3.8.3=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python-engineio=3.11.2=py_0
  - python-socketio=4.4.0=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - readline=8.0=h1de35cc_0
  - requests=2.22.0=py38_1
  - setuptools=47.3.1=py38_0
  - six=1.14.0=py38_0
  - sqlalchemy=1.3.13=py38h1de35cc_0
  - sqlite=3.32.3=hffcf06c_0
  - sqlparse=0.3.0=py_0
  - tk=8.6.10=hb0a8c7a_0
  - urllib3=1.25.8=py38_0
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h1990bb4_3
  - pip:
    - image==1.5.28
    - pycryptodomex==3.9.8
    - pyjwt==1.7.1
    - stream-chat==1.3.1
prefix: /Users/nicklin/opt/anaconda3/envs/housing

